name: "Bug Report"
description: File a reproducible bug encountered while building with WebSpatial
labels: ["bug", "feature"]
assignees: []
body:
  - type: checkboxes
    id: duplicates
    attributes:
      label: Duplicate check
      description: Please confirm you searched existing issues and the FAQs.
      options:
        - label: "I searched existing issues and discussions"

  - type: textarea
    id: actual
    attributes:
      label: Steps & Expected vs Actual Behavior
      description: Describe how to reproduce the bug, what output you expected, and what actually happened. Screenshots, console logs, and errors help speed up resolution!
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Dev Environment
      description: |
        **Commands to find versions:**

        **Node.js version**
        ```bash
        node -v
        ```

        **WebSpatial & Vite packages**
        ```bash
        cd your-project-folder/
        npm ls @webspatial/react-sdk @webspatial/core-sdk @webspatial/vite-plugin \
        @webspatial/builder @webspatial/platform-visionos vite vite-plugin-html react react-dom
        ```
      value: |
        • Run Target (Vision Pro / Simulator / Browser):
        • OS:
        • Node.js version:
        • WebSpatial & Vite versions:
    validations:
      required: true
