name: "Bug Report"
description: File a reproducible bug encountered while building with WebSpatial
labels: ["bug", "feature"]
assignees: []
body:
  - type: checkboxes
    id: duplicates
    attributes:
      label: Duplicate check
      description: Please confirm you searched existing issues and the FAQs.
      options:
        - label: "I searched existing issues and discussions"

  - type: textarea
    id: summary
    attributes:
      label: Summary
      placeholder: "One-two sentences describing the bug"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce

  - type: textarea
    id: actual
    attributes:
      label: Expected vs Actual Behavior
      description: Describe expected and actual behaviour. Attaching screenshots and console logs is highly recommended for faster resolution.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Dev Environment
      description: |
        **Add your device and OS details.** Example: macOS 14.6.1 (Apple Silicon or Intel)

        **Paste the output of the following terminal commands**

        **Node.js version**
        ```bash
        node -v
        ```

        **WebSpatial & Vite packages**
        ```bash
        cd your-project-folder/
        npm ls @webspatial/react-sdk @webspatial/core-sdk @webspatial/vite-plugin \
        @webspatial/builder @webspatial/platform-visionos vite vite-plugin-html react react-dom
        ```
      value: |
        • Run Target (Vision Pro / Simulator / Browser):
        • OS:
        • Node.js version:
        • WebSpatial & Vite versions:
    validations:
      required: true
