name: "Bug Report"
description: File a reproducible bug encountered while building with WebSpatial
labels: ["bug", "feature"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug! Please fill in all required fields so triage is fast.

  - type: checkboxes
    id: duplicates
    attributes:
      label: Duplicate check
      description: Please confirm you searched existing issues and the FAQs.
      options:
        - label: "I searched existing issues and discussions"

  - type: textarea
    id: summary
    attributes:
      label: Summary
      placeholder: "One-two sentences describing the bug"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Exact steps to reproduce the bug are required. Attaching screenshots and console logs is highly recommended for faster resolution.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: Describe what you thought would happen if everything worked correctly.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: Describe what really happened, including error messages or incorrect output.
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - "S0 - Blocking (cannot proceed / demo-blocker)"
        - "S1 - Major (workaround exists but risky)"
        - "S2 - Minor (no data loss)"
        - "S3 - Documentation"

  - type: textarea
    id: environment
    attributes:
      label: Environment & Versions
      description: |
        **Add your OS details.** Example: macOS 14.6.1 (Apple Silicon or Intel)

        **Paste the output of the following terminal commands**
        **Node.js version**
        ```bash
        node -v
        ```

        **WebSpatial & Vite packages**
        ```bash
        cd your-project-folder/
        npm ls @webspatial/react-sdk @webspatial/core-sdk @webspatial/vite-plugin \
        @webspatial/builder @webspatial/platform-visionos vite vite-plugin-html react react-dom
        ```
    validations:
      required: true